"""your message

Revision ID: a20dbc757638
Revises: 544c7e6aabc0
Create Date: 2026-04-05 23:18:49.474468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a20dbc757638'
down_revision: Union[str, Sequence[str], None] = '544c7e6aabc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('soft_delete', sa.Integer(), nullable=True))
    op.add_column('test', sa.Column('soft_delete', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test', 'soft_delete')
    op.drop_column('question', 'soft_delete')
    # ### end Alembic commands ###
